# Generated by Django 5.2.6 on 2025-09-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('from_unit', models.CharField(choices=[('C', 'Celsius'), ('F', 'Fahrenheit'), ('K', 'Kelvin')], max_length=1)),
                ('to_unit', models.CharField(choices=[('C', 'Celsius'), ('F', 'Fahrenheit'), ('K', 'Kelvin')], max_length=1)),
                ('result', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
