# Generated by Django 5.2.8 on 2025-11-09 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=255)),
                ('Last_name', models.CharField(max_length=255)),
                ('Email', models.EmailField(max_length=255)),
                ('City', models.CharField(max_length=255)),
            ],
        ),
    ]
